(
SELECT
    AGENDA_CONSULTA.NR_SEQUENCIA AS sequenciaAgenda,
    AGENDA_CONSULTA.NM_PACIENTE,
    PESSOA_FISICA.CD_PESSOA_FISICA AS cdPessoaFisica,
    CONCAT(PESSOA_FISICA.NR_DDD_CELULAR, PESSOA_FISICA.NR_TELEFONE_CELULAR) telPaciente,
    COALESCE(P.NM_PESSOA_FISICA, 'Médico não identificado') as nmMedico,
    TO_CHAR(AGENDA_CONSULTA.DT_AGENDA, 'DD/MM/YYYY') as dtAgenda,
    TO_CHAR(AGENDA_CONSULTA.DT_AGENDA, 'HH24:MI') as hrAgenda,
    TO_CHAR(PESSOA_FISICA.DT_NASCIMENTO, 'YYYY-MM-DD') as dtNascimento,
    CD_TIPO_AGENDA,
    IE_STATUS_AGENDA,
    AGENDA.CD_ESTABELECIMENTO
FROM
    TASY.AGENDA_CONSULTA
INNER JOIN TASY.PESSOA_FISICA ON
    PESSOA_FISICA.CD_PESSOA_FISICA = AGENDA_CONSULTA.CD_PESSOA_FISICA
INNER JOIN TASY.AGENDA ON
    AGENDA.CD_AGENDA = AGENDA_CONSULTA.CD_AGENDA
LEFT JOIN TASY.PESSOA_FISICA P ON
    P.CD_PESSOA_FISICA = AGENDA.CD_PESSOA_FISICA
LEFT JOIN TASY.ESPECIALIDADE_MEDICA ON
    ESPECIALIDADE_MEDICA.CD_ESPECIALIDADE = AGENDA.CD_ESPECIALIDADE
WHERE
    AGENDA.CD_TIPO_AGENDA = 3
    AND TASY.AGENDA.CD_AGENDA NOT IN ('5454', '5455', '5463', '5465', '5466', '5464', '5492', '5495','4762','6392','6093','4223','6546')
    AND P.NM_PESSOA_FISICA NOT IN ('Josiane Zilma de Souza', 'Anajara Tatiana Fortes')
    AND AGENDA_CONSULTA.IE_CLASSIF_AGENDA NOT IN ('83', '139', '153', '33', '43', '169', '93', '201', '238', '198', '162', '117', '213', '91', '92', '170', 'R', '47', '48', '49', '50', '128', '175', 'C','20','222','223','216')
    AND TO_CHAR(AGENDA_CONSULTA.DT_AGENDA, 'YYYY-MM-DD') = TO_CHAR(CURRENT_DATE + 2, 'YYYY-MM-DD')
    AND PESSOA_FISICA.NR_TELEFONE_CELULAR IS NOT NULL
    AND CD_CONVENIO NOT IN (184) 
    AND IE_STATUS_AGENDA = 'N'
    AND DT_CONFIRMACAO IS NULL
)
UNION
(
SELECT
    A.NR_SEQUENCIA AS sequenciaAgenda,
    A.NM_PACIENTE,
    PESSOA_FISICA.CD_PESSOA_FISICA AS cdPessoaFisica,
    CONCAT(PESSOA_FISICA.NR_DDD_CELULAR, PESSOA_FISICA.NR_TELEFONE_CELULAR) telPaciente,
    COALESCE(P.NM_PESSOA_FISICA, 'Médico não identificado') as nmMedico,
    TO_CHAR(A.DT_AGENDA, 'DD/MM/YYYY') as dtAgenda,
    TO_CHAR(A.HR_INICIO, 'HH24:MI') as hrAgenda,
    TO_CHAR(PESSOA_FISICA.DT_NASCIMENTO, 'YYYY-MM-DD') as dtNascimento,
    CD_TIPO_AGENDA,
    IE_STATUS_AGENDA,
    AGENDA.CD_ESTABELECIMENTO
FROM
    TASY.AGENDA_PACIENTE A
INNER JOIN TASY.PESSOA_FISICA ON
    PESSOA_FISICA.CD_PESSOA_FISICA = A.CD_PESSOA_FISICA
INNER JOIN TASY.AGENDA ON
    AGENDA.CD_AGENDA = A.CD_AGENDA
LEFT JOIN TASY.PESSOA_FISICA P ON
    P.CD_PESSOA_FISICA = AGENDA.CD_PESSOA_FISICA
LEFT JOIN TASY.ESPECIALIDADE_MEDICA ON
    ESPECIALIDADE_MEDICA.CD_ESPECIALIDADE = AGENDA.CD_ESPECIALIDADE
WHERE
    AGENDA.CD_TIPO_AGENDA = 2
    AND TASY.AGENDA.CD_AGENDA NOT IN ('5454', '5455', '5463', '5465', '5466', '5464', '5492', '5495','4762','6392','6093','4223','6546')
    AND P.NM_PESSOA_FISICA NOT IN ('Josiane Zilma de Souza', 'Anajara Tatiana Fortes')
    AND TO_CHAR(A.DT_AGENDA, 'YYYY-MM-DD') = TO_CHAR(CURRENT_DATE + 2, 'YYYY-MM-DD')
    AND PESSOA_FISICA.NR_TELEFONE_CELULAR IS NOT NULL
    AND IE_STATUS_AGENDA = 'N'
    AND CD_CONVENIO NOT IN (184) 
    AND DT_CONFIRMACAO IS NULL
    AND (
        A.CD_AGENDA NOT IN (48, 5005, 5323, 51, 5006, 5343, 44, 5003)
        OR A.IE_AUTORIZACAO NOT IN ('AI', 'B', 'G', 'CS', 'EA', 'GP', 'N', 'NP', 'P', 'PA', 'PN', 'PZ', 'RS', 'SA')
    )
)